# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hASWXhNyYtJRIY53e7AFes96utntneLK
"""

#code snippet 1
# Install required libraries (only needed if not installed in the environment)
!pip install streamlit
!pip install pycaret

#code snippet 2
# Import libraries for the Streamlit app
import streamlit as st
import pandas as pd
from pycaret.classification import load_model, predict_model

#code snippet 3
# Load the saved model
model = load_model('/content/ebook_subscription_model')

#code snippet 4
# Title and intro
st.title("📚 E-Book Subscription Prediction")
st.write("Enter customer details to predict subscription likelihood.")

#code snippet 5
# User inputs - categorical features
education = st.selectbox("Education Level", ["High School", "Bachelors", "Masters", "Doctorate", "Other"])
occupation = st.selectbox("Occupation", ["Professional", "Management", "Clerical", "Manual", "Other"])
gender = st.selectbox("Gender", ["Male", "Female", "Other"])
marital = st.selectbox("Marital Status", ["Single", "Married", "Divorced", "Widowed"])
home_owner = st.radio("Home Owner Status (0 = No, 1 = Yes)", [0, 1])

#code snippet 6
# User inputs - numerical features
cars = st.number_input("Number of Cars Owned", min_value=0, max_value=5, value=1)
children_home = st.number_input("Number of Children At Home", min_value=0, max_value=10, value=0)
children_total = st.number_input("Total Number of Children", min_value=0, max_value=10, value=0)
income = st.number_input("Annual Income ($)", min_value=0, max_value=500000, value=50000)
spend = st.number_input("Avg Monthly Spend ($)", min_value=0, max_value=5000, value=200)
age = st.number_input("Age", min_value=18, max_value=100, value=30)

#code snippet 6
# User inputs - location features
city = st.text_input("City", "Dallas")
zipcode = st.text_input("ZipCode", "75287")
state = st.text_input("State", "TX")

#code snippet 7
# Build dataframe with inputs
input_data = pd.DataFrame({
    'Education Level': [education],
    'Occupation': [occupation],
    'Gender': [gender],
    'Marital Status': [marital],
    'Home Owner Status': [home_owner],  # 0 = No, 1 = Yes
    'Number of Cars Owned': [cars],
    'Number of Children At Home': [children_home],
    'Total Number of Children': [children_total],
    'Annual Income': [income],
    'Avg Monthly Spend': [spend],
    'City': [city],
    'ZipCode': [zipcode],
    'State': [state],
    'Age': [age]
})

#code snippet 8
# Prediction button
if st.button("Predict"):
    prediction = predict_model(model, data=input_data)
    label = prediction['prediction_label'][0]
    score = prediction['prediction_score'][0]

    st.subheader(f"Result: {label}")
    st.write(f"Probability of subscription: {score:.2f}")